### ISSUE TITLE
calling local IPs

### ISSUE THREAD

**Issue by snizzleorg** [nmattisson/HttpClient#17]
I'm trying to call a local IP but no success. I can call the same server if I forward the port and use the external IP. however using the local IP I cannot get any connection - Any idea why this may be?

**Comment by grrodre** [comment]
Same issue here. I think it has to do with the WiFi chip and firmware itself. If you ping from your local server to the Spark ip you wont have a response but then Spark will be able to connect to that IP.

Regards.Greg.

**Comment by nmattisson** [comment]
This is probably a problem lower in the stack. Have you tried using the TCP library to see if the problem persists?
