### ISSUE TITLE
passing authorisation credential

### ISSUE THREAD

**Issue by snizzleorg** [nmattisson/HttpClient#18]
Is it possible to pass authorisation credentials?

**Comment by crunchie84** [comment]
Have you tried adding the header yourself?
```
http_header_t headers[] = {
      { "Content-Type", "text/plain" },
      { "Authorization", "Basic NWYYDKYUKY5OWJlZDUtZNmOg=="},
      { "Accept", "*/*" }
      //{ "X-Auth-Token" , TOKEN },
    { NULL, NULL } // NOTE: Always terminate headers will NULL
};
```

**Comment by snizzleorg** [comment]
Yes I tried but actually the problem was due to https, which httpclient does not support as far as I know. That was the reason it did not work.

**Comment by nmattisson** [comment]
Since the Spark Core didn't support https, I couldn't add it to HttpClient either. Pull requests are welcome if someone wants to add it to future revisions now that the new hardware supports it.
