### ISSUE TITLE
'millis' was not declared in this scope

### ISSUE THREAD

**Issue by zoltangbereczky** [nmattisson/HttpClient#19]
Veryfing code using this library in Particle Build fails with this error:
```
HttpClient/HttpClient.cpp:172:37: error: 'millis' was not declared in this scope
     unsigned long lastRead = millis()
HttpClient/HttpClient.cpp:231:22: error: 'delay' was not declared in this scope
             delay(200);
HttpClient/HttpClient.cpp:266:47: error: 'atoi' was not declared in this scope
             aResponse.status = atoi(statusCode.c_str());

**Comment by ilessiivi** [comment]
I ran into this problem myself and as suggested [here](https://community.particle.io/t/libraries-to-update-for-the-photon/12000/18), HttpClient.h needs to have ```#include "application.h"``` in order to work on Photons. I created the pull request #20 for this.
