### ISSUE TITLE
Update particle.io library

### ISSUE THREAD

**Issue by tominthevan** [nmattisson/HttpClient#22]
Hi Nils

The version of the HttpClient in the particle.io library does not compile for the photon. This was fixed by pull request #20 which has been merged into the master. I asked particle.io why they don't have the latest version and the response was that you would have to resubmit the library.

Is there any chance you could do that. It would save us novices some time trying to figure out what's wrong when we run into this little problem.

Thanks
Tom

**Comment by nmattisson** [comment]
I've never used the Web IDE so I'm not completely familiar with the process, but I bumped the version number which will hopefully trigger Particle to consider it resubmitted. If there is anything else I need to do, just give me a pointer.
