### ISSUE TITLE
'delay' was not declared in this scope

### ISSUE THREAD

**Issue by momo96** [nmattisson/HttpClient#24]
Veryfing code using this library in Particle Build fails with this error:
```
HttpClient/HttpClient.cpp:231:22: error: 'delay' was not declared in this scope
             delay(200)

**Comment by nmattisson** [comment]
This should be fixed by https://github.com/nmattisson/HttpClient/pull/20
Are you on the latest version?

**Comment by Redland08** [comment]
Hello, Im having the same issue with my Photon. How do I upload the updated one to my library?

**Comment by nmattisson** [comment]
Try re-importing the library. I bumped the version available in the Web IDE this morning.

**Comment by Redland08** [comment]
It worked! Thank You...

**Comment by nmattisson** [comment]
You're welcome.
